#!/bin/bash

# ropegun/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

ropegun/bootstrap
ropegun/start build
ropegun/update
